#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=${YNH_APP_INSTANCE_NAME:-$YNH_APP_ID}

#=================================================
# SPECIFIC ACTION
#=================================================
# REMOVE THE DATABASE
#=================================================
ynh_script_progression --message="Removing the database..." --weight=9

db_name=$(ynh_app_setting_get  --app=$app --key=db_name)
ynh_psql_remove_db --db_user=$db_name --db_name=$db_name


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Execution completed" --last
